Joseph Bravo / completed: array-manipulation-2
joseph-bravo/c0322-code-solutions pull request #41
Opened 2022-03-25 22:29 UTC by joseph-bravo

<img width="486" alt="image" src="https://user-images.githubusercontent.com/78003700/160210338-78d594f0-15b4-4f83-b809-f9b6eca8f341.png">

2022-03-25 23:03 UTC, codingcodymiller requested changes

2022-03-25 23:03 UTC, codingcodymiller commented on array-manipulation-2/src/take-right.js
> +  for (var i = 0; i < count && (array.length - i - 1 >= 0); i++) {
This is pretty complicated. I would just start the loop at `array.length - count`, that can help you simplify this by a lot.

2022-03-25 23:32 UTC, joseph-bravo commented on array-manipulation-2/src/take-right.js
> +    }
!

2022-03-26 00:20 UTC, codingcodymiller requested changes

2022-03-26 00:20 UTC, codingcodymiller commented on array-manipulation-2/src/take-right.js
> +  for (var i = array.length - count; i < array.length; i++) {
How about `var i = Math.max(0, array.length - count)`?

If you do this, you can remove the need to have a conditional within the loop

2022-03-26 00:38 UTC, joseph-bravo commented
<img width="951" alt="image" src="https://user-images.githubusercontent.com/78003700/160217570-326ab903-8ee1-497b-bb20-302650122df3.png">

2022-03-26 01:14 UTC, codingcodymiller approved these changes

2022-03-28 17:28 UTC, merged